--Platform tablosu için gerekli insert komutlarý

INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (1,'WINDOWS','MICROSOFT','PC');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (2,'NINTENDO SWITCH','NINTENDO','MOBILE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (3,'PLAYSTATION 4','SONY','CONSOLE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (4,'XBOX ONE X','MICROSOFT','CONSOLE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (5,'PLAY STORE','GOOGLE','MOBILE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (6,'LINUX','LINUX','PC');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (7,'MAC OS','APPLE','PC');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (8,'STADIA','GOOGLE','CONSOLE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (9,'APP STORE','APPLE','MOBILE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (10,'PLAYSTATION VITA','SONY','MOBILE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (11,'XBOX SERIES X','MICROSOFT','CONSOLE');
INSERT INTO GAMELIST.PLATFORM (PLATFORM_ID,PLATFORM_NAME,BRAND,CATEGORY) VALUES (12,'PLAYSTATION 5','SONY','CONSOLE');
